import 'server-only';

import { z } from 'zod';

/**
 * Server-side configuration.
 *
 * `server-only` makes an accidental client import a build error rather than a
 * silent credential leak. Nothing here is prefixed `NEXT_PUBLIC_`, so nothing
 * here is inlined into the browser bundle.
 */

/**
 * `.env.example` ships every key with an empty value, so a copied file yields
 * `KEY=''` for everything. Empty and whitespace-only values mean "not set",
 * otherwise every default in the schema below would be bypassed.
 */
function normalize(source: EnvSource): Record<string, string | undefined> {
  const output: Record<string, string | undefined> = {};
  for (const [key, value] of Object.entries(source)) {
    const trimmed = value?.trim();
    output[key] = trimmed === undefined || trimmed.length === 0 ? undefined : trimmed;
  }
  return output;
}

const booleanFlag = z
  .enum(['true', 'false', '1', '0'])
  .transform((value) => value === 'true' || value === '1');

const csvList = z
  .string()
  .transform((value) =>
    value
      .split(',')
      .map((entry) => entry.trim())
      .filter((entry) => entry.length > 0),
  )
  .pipe(z.array(z.url({ protocol: /^https?$/ })));

const envSchema = z.object({
  ALCHEMY_API_KEY: z.string().min(8).optional(),

  // Per-chain RPC overrides. Each falls back to public, keyless endpoints.
  ETHEREUM_RPC_URLS: csvList.optional(),
  BASE_RPC_URLS: csvList.optional(),
  ARBITRUM_RPC_URLS: csvList.optional(),
  OPTIMISM_RPC_URLS: csvList.optional(),
  BSC_RPC_URLS: csvList.optional(),

  /**
   * Age at which a bundled token list is called out as possibly missing
   * recently listed tokens. The lists are regenerated by hand today, so the
   * default is deliberately shorter than the interval at which a forgotten list
   * would start to matter — a stale list understates a portfolio silently, and
   * silence is the failure mode this project exists to avoid.
   */
  TOKEN_LIST_MAX_AGE_DAYS: z.coerce.number().int().positive().max(3_650).default(60),

  /** CoinGecko Demo key. Absent means prices are simply not cross-checked. */
  COINGECKO_API_KEY: z.string().min(8).optional(),
  /**
   * Shared secret for `POST /api/snapshot`. Absent means the endpoint reports 404 and no
   * history is taken — the whole feature is off rather than merely unlocked.
   */
  NUXFOLIO_SNAPSHOT_KEY: z.string().min(16).optional(),
  /** Relative difference between two sources before a quote is called disputed. */
  PRICE_DISPUTE_TOLERANCE: z.coerce.number().min(0).max(1).default(0.02),
  /** Share of the priced subtotal a cross-check should cover. */
  PRICE_CROSSCHECK_COVERAGE: z.coerce.number().min(0).max(1).default(0.95),
  /** Per-chain ceiling on assets sent to the verifier, bounding quota spend. */
  /**
   * Per-chain ceiling on assets given a historical lookup. Bounds request count:
   * each selected asset costs two batched calls' worth of refs, and the asset cap
   * (400) would otherwise allow 14 calls per chain.
   */
  PRICE_HISTORY_MAX_ASSETS: z.coerce.number().int().min(0).max(400).default(50),

  PRICE_CROSSCHECK_MAX_ASSETS: z.coerce.number().int().positive().max(500).default(25),

  PRICE_CONFIDENCE_MIN: z.coerce.number().min(0).max(1).default(0.7),
  PRICE_MAX_AGE_SECONDS: z.coerce.number().int().positive().default(3_600),

  PORTFOLIO_CACHE_TTL_SECONDS: z.coerce.number().int().positive().max(3_600).default(60),
  PORTFOLIO_CACHE_MAX_ENTRIES: z.coerce.number().int().positive().default(500),

  RATE_LIMIT_MAX_REQUESTS: z.coerce.number().int().positive().default(30),
  RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
  TRUST_PROXY_HEADERS: booleanFlag.default(false),
  CLIENT_IP_HEADER: z.string().min(1).default('x-forwarded-for'),

  /** Wall-clock budget for all upstream work in one API request. */
  REQUEST_DEADLINE_MS: z.coerce.number().int().positive().max(60_000).default(15_000),
  /** Hard ceiling on assets processed per chain, to bound fan-out. */
  MAX_ASSETS_PER_PORTFOLIO: z.coerce.number().int().positive().max(5_000).default(400),

  /**
   * Chains scanned concurrently when a request asks for all networks. Each
   * chain already runs its own bounded token sweep, so this multiplies total
   * in-flight upstream work and is kept deliberately small.
   */
  CHAIN_SCAN_CONCURRENCY: z.coerce.number().int().positive().max(10).default(3),

  LOG_LEVEL: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
});

export type ServerEnv = z.infer<typeof envSchema>;

/**
 * A plain string map rather than `NodeJS.ProcessEnv`, whose required `NODE_ENV`
 * would make an empty source untypeable in tests.
 */
export type EnvSource = Readonly<Record<string, string | undefined>>;

/** Pure and testable: parses an arbitrary environment source. */
export function parseServerEnv(source: EnvSource): ServerEnv {
  const result = envSchema.safeParse(normalize(source));
  if (!result.success) {
    // Reports which keys are wrong without echoing their values, so a bad key
    // never lands in a crash log.
    const keys = [...new Set(result.error.issues.map((issue) => issue.path.join('.')))];
    throw new Error(`Invalid environment configuration for: ${keys.join(', ')}`);
  }
  return result.data;
}

let cached: ServerEnv | undefined;

export function getServerEnv(): ServerEnv {
  cached ??= parseServerEnv(process.env);
  return cached;
}

/**
 * Literal secret values the logger must scrub. Kept next to the schema so a
 * newly added credential is one edit away from being redacted.
 *
 * Operator-configured RPC URLs are included because a keyed endpoint embeds its
 * credential in the path, where no pattern can distinguish it from a route
 * segment. Providers already log opaque labels rather than URLs; this is the
 * second layer, for the case where one day something does not. The built-in
 * public defaults are not registered — they are not secret, and scrubbing them
 * would only make an operator's logs harder to read.
 */
export function getSecretValues(env: ServerEnv = getServerEnv()): string[] {
  return [
    env.ALCHEMY_API_KEY,
    env.COINGECKO_API_KEY,
    env.NUXFOLIO_SNAPSHOT_KEY,
    ...(env.ETHEREUM_RPC_URLS ?? []),
    ...(env.BASE_RPC_URLS ?? []),
    ...(env.ARBITRUM_RPC_URLS ?? []),
    ...(env.OPTIMISM_RPC_URLS ?? []),
    ...(env.BSC_RPC_URLS ?? []),
  ].filter((value): value is string => typeof value === 'string');
}
